name: Deploy to AWS

on:
  push:
    branches: ["main"]
env:
  CDK_VERSION: "2.126.0"
  AWS_ACCOUNT_ID: 975050052132
  AWS_REGION: eu-north-1
  API_KEY: ${{ secrets.API_KEY }}  
  APPLICATION_TAG: ${{ vars.APPLICATION_TAG }}
  APPLICATION_NAME: "selenium-lambda"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050052132:role/otto
          role-session-name: github-action-role
          aws-region: eu-north-1

      - name: Bootstrap
        run: |
          . _CI/bootstrap.sh

      - name: Deploy
        run: |
          . _CI/deploy.sh
